export const MAPLE_VAR_COLOR = {
  body: '#fff',
  alpha: '#000',
  beta: '#333',
  link: '#1a6fba',
  danger: '#b00',
  dark: '#212529',
  info: '#17a2b8',
  light: '#f0f0f0',
  muted: '#ccc',
  success: '#44602d',
  warning: '#ffc107',
  black: '#000',
  white: '#fff',
  inherit: 'inherit',
  transparent: 'transparent',
  currentColor: 'currentColor',
};
