export declare const MAPLE_VAR_FONT_SIZE: {
    h1: string;
    h2: string;
    h3: string;
    h4: string;
    h5: string;
    h6: string;
    p1: string;
    p2: string;
    p3: string;
    p4: string;
    p5: string;
    p6: string;
    i1: string;
    i2: string;
    i3: string;
    i4: string;
    i5: string;
    i6: string;
};
