export declare const MAPLE_VAR_SPACER: {
    auto: string;
    n9: string;
    n8: string;
    n7: string;
    n6: string;
    n5: string;
    n4: string;
    n3: string;
    n2: string;
    n1: string;
    0: number;
    1: string;
    2: string;
    3: string;
    4: string;
    5: string;
    6: string;
    7: string;
    8: string;
    9: string;
    gutter: string;
    'n-gutter': string;
    'gutter-half': string;
    'n-gutter-half': string;
};
